# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_Rz7PeHTUL4diOhp4Jq9i1Qf7pu6V9QH

### **Data Cleaning Steps**

## **Step1: Data collection and inspection(explore)**
"""

import numpy as pd
import pandas as pd
import matplotlib.pyplot as plt

df =pd.read_excel("/content/messysalesData.xlsx")

df

df.info()

df.describe()

df.shape

df.isnull().sum()

df.isnull().sum()/len(df)*100

df[df.duplicated].shape

df[df.duplicated()]

for col in df.columns:
  if df[col].nunique() < 20: #nunique will tell us about the no. of unique values
    print (df[col].value_counts()) # value_counts will tell the freqyency
    print('-'*50)

"""## **step:2 Handling Missing Values**"""

df.dropna(subset=['Age'], inplace=True)

df.isnull().sum()

df.isnull()

df['Age'].unique()

# now we have import rejex
import re

def extract_age(age):
  age_num = re. findall('[0-9]+', str(age))
  if len(age_num) > 0:
    return age_num[0]

  else:
    return age

# Apply Function
df['Age'] = df['Age'].apply(lambda x: extract_age(x))

df['Age'].unique()

# Convert to numeric first
df['Age'] = pd.to_numeric(df['Age'])

# Replace unrealistic ages
df.loc[df['Age'] > 100, 'Age'] = df['Age'].median()

df['Age'].unique()

df.dropna(subset=['Sales'], inplace=True)

df.isnull().sum()

"""## **Step:3 Fixing Inconsistent Formatting**"""

# inconsist formating like(M, m, Male, F, f, Female)

df['Gender'].unique()

df['Gender'].str.lower().str.strip().unique()

print(df['Gender'].unique())

df['Gender'] = df['Gender'].str.lower().str.strip()

pip install gender-guesser

import gender_guesser.detector as gender

df['Gender'].replace({'f':'female', 'm':'male'}, inplace = True)

df

"""## **Step4: Handling Duplicate Values**"""

df[df.duplicated].shape

df['Age'].value_counts()

df.shape

"""## **Step:5 Crrecting Data types**"""

df['Age'].astype('int64')

df.columns

df['Sales'] = df['Sales'].replace('Not Available', 0).astype(float)

df['Transaction_Date'] = pd.to_datetime(df['Transaction_Date'])

df.info()

"""## **Last Step: Handling Outliers**"""

import seaborn as sns

import matplotlib.pyplot as plt
import seaborn as sns

cols = ['Age', 'Sales']

plt.figure(figsize=(12, 5)) # Adjusted width for 2 plots

# Corrected the loop to unpack both index (i) and the column name (col)
for i, col in enumerate(cols, 1):
    plt.subplot(1, 2, i) # Changed to 1 row, 2 columns to match 'cols' length
    df_clean = df.copy()
    sns.boxplot(y=df[col], color='skyblue', width=0.3)

    # Added missing comma before fontsize
    plt.title(f'Boxplot of {col}', fontsize=12)
    plt.ylabel('')
    plt.grid(axis='y', linestyle='--', alpha=0.6)

plt.tight_layout()
plt.show()

from scipy import stats
stats.zscore(df_clean['Sales'])

import numpy as np
np.abs(stats.zscore(df_clean['Sales']))

z_scores = np.abs(stats.zscore(df_clean['Sales']))

(z_scores > 3).any()

df

df_clean = df[~(z_scores > 3)]

df_clean.shape

# Calculate absolute Z-scores for our columns
# Using pd.to_numeric first ensures we don't have strings
for col in ['Age', 'Sales']:
    df_clean[col] = pd.to_numeric(df_clean[col], errors='coerce')

# Filter out rows where Z-score > 3
z_scores = np.abs(stats.zscore(df_clean[['Age', 'Sales']], nan_policy='omit'))
df_clean = df_clean[(z_scores < 3).all(axis=1)]

# 2. PLOT THE CLEANED DATA
cols = ['Age', 'Sales']
plt.figure(figsize=(12, 5))

for i, col in enumerate(cols, 1):
    plt.subplot(1, 2, i)
    # Use df_clean here, not df!
    sns.boxplot(y=df_clean[col], color='skyblue', width=0.3)

    plt.title(f'Cleaned Boxplot of {col}', fontsize=12)
    plt.ylabel('')
    plt.grid(axis='y', linestyle='--', alpha=0.6)

plt.tight_layout()
plt.show()

